#!/usr/bin/env bash

echo "COMPILING HASKELL CODE, GENERATING DATA"
cd backend
stack build
stack exec epmerge -- --generateAll --generateElm --print
cd ../frontend
echo "STARTING ELM SERVER"
elm-live src/Main.elm  --open -- --debug

