name:                haskell-master
version:             0.1.0.0
github:              "eirikhalvard/haskell-master"
license:             BSD3
author:              "Eirik Halvard Sæther"
maintainer:          "eirik.halvard.95@gmail.com"
copyright:           "2019 Eirik Halvard Sæther"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Haskell implementation of my master thesis
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/eirikhalvard/haskell-master#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- containers
- lens
- lens-aeson
- mtl
- text
- raw-strings-qq
- prettyprinter
- pretty-simple
- hspec
- QuickCheck

ghc-options:
  - -fwarn-incomplete-patterns

default-extensions:
- TemplateHaskell
- QuasiQuotes
- OverloadedStrings

library:
  source-dirs: src

executables:
  haskell-master-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-master

tests:
  haskell-master-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-master
